### ISSUE TITLE
Strings are not correct

### ISSUE THREAD

**Issue by lovedebug** [remnoteio/translation#19]
1. some strings are listed in list, they are not divided into separate string, is this by design? those keys are marked as "KEYWORDS" in the end.

[SETTINGS.ACCOUNT.EXPORT_IMPORT_KEYWORDS](https://inlang.com/editor/github.com/lovedebug/translation?id=SETTINGS.ACCOUNT.NAVIGATION_KEYWORDS)

https://inlang.com/editor/github.com/lovedebug/translation?id=SETTINGS.ACCOUNT.EXPORT_IMPORT_KEYWORDS

https://inlang.com/editor/github.com/lovedebug/translation?id=SETTINGS.ACCOUNT.AUTHENTICATION_KEYWORDS

https://inlang.com/editor/github.com/lovedebug/translation?id=SETTINGS.ACCOUNT.ADVANCED_KEYWORDS

https://inlang.com/editor/github.com/lovedebug/translation?id=SETTINGS.ACCOUNT.DANGER_ZONE.KEYWORDS

https://inlang.com/editor/github.com/lovedebug/translation?id=SETTINGS.ACCOUNT.SUPPORT.KEYWORDS

https://inlang.com/editor/github.com/lovedebug/translation?id=SETTINGS.PLANS.KEYWORDS

https://inlang.com/editor/github.com/lovedebug/translation?id=SETTINGS.EARN_CREDIT.KEYWORDS

https://inlang.com/editor/github.com/lovedebug/translation?id=SETTINGS.GLOBAL_INTERFACE.IN_APP_SUGGESTIONS.TITLE

https://inlang.com/editor/github.com/lovedebug/translation?id=SETTINGS.GLOBAL_INTERFACE.IN_APP_SUGGESTIONS.KEYWORDS

https://inlang.com/editor/github.com/lovedebug/translation?id=SETTINGS.GLOBAL_INTERFACE.ONBOARDING_TIPS.KEYWORDS

https://inlang.com/editor/github.com/lovedebug/translation?id=SETTINGS.GLOBAL_INTERFACE.COMMUNITY_DOCUMENT_SEARCH_LANGUAGE.KEYWORDS

https://inlang.com/editor/github.com/lovedebug/translation?id=SETTINGS.GLOBAL_INTERFACE.INTERFACE.KEYWORDS

2. wrong string
![image](https://github.com/remnoteio/translation/assets/5045252/cc3c9b24-ec89-4225-97dc-112de7593820)

**Comment by trend-howie-zhang** [comment]
@dewil-official How about those strings?

**Comment by dewil-official** [comment]
Will fix #1 now.

#2 is already solved.

Thank you!
